const { options } = require('../../constants/swagger');
const { responses } = require('../../utils/responses/swagger');

options.tags = ['Defines'];

module.exports = {
  '/defines': {
    get: {
      ...options,
      description: 'Get defines',
      responses: responses({
        defines: {
          type: 'array',
          items: {
            type: 'object',
            properties: {
              purposeStatement: { type: 'integer' },
              year: { type: 'string' },
              city: { type: 'string' },
              familyClass: { type: 'string' },
              familyRelations: { type: 'string' },
              immediateFamily: { type: 'string' },
              college: { type: 'string' },
              major: { type: 'string' },
              industry: { type: 'string' },
              position: { type: 'string' },
              childLove: { type: 'string' },
              career: { type: 'string' },
              momInspired: { type: 'string' },
              momTaught: { type: 'string' },
              dadInspired: { type: 'string' },
              dadTaught: { type: 'string' },
              parentsLesson: { type: 'string' },
              adultDecision: { type: 'string' },
              adversity: { type: 'string' },
              talent1: { type: 'string' },
              talent2: { type: 'string' },
              talent3: { type: 'string' },
              teachAbout: { type: 'string' },
              improveArea: { type: 'string' },
              passion1: { type: 'string' },
              passion2: { type: 'string' },
              passion3: { type: 'string' },
              passion4: { type: 'string' },
              peopleHelp: { type: 'string' },
              helpReason: { type: 'string' },
              purposeFinal: { type: 'string' },
              teamFeedback: { type: 'string' },
              purposeVerb: { type: 'string' },
              purposeComponent: { type: 'string' },
            },
          },
        },
      }),
    },
    post: {
      ...options,
      description: 'Create or update Define',
      responses: responses(),
      parameters: [{
        in: 'body',
        name: 'purposeStatement',
        required: false,
        type: 'integer',
        min: 1,
        max: 7,
        example: 1,
      }, {
        in: 'body',
        name: 'year',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'city',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'familyClass',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'familyRelations',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'immediateFamily',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'college',
        required: false,
        type: 'string',
      }, {
        in: 'body',
        name: 'major',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'industry',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'position',
        required: false,

        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'childLove',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'career',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'momInspired',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'momTaught',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'dadInspired',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'dadTaught',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'parentsLesson',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'adultDecision',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'adversity',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'talent1',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'talent2',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'talent3',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'teachAbout',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'improveArea',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'passion1',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'passion2',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'passion3',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'passion4',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'peopleHelp',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'helpReason',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'purposeFinal',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'teamFeedback',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'purposeVerb',
        required: false,
        type: 'string',
        example: 'string',
      }, {
        in: 'body',
        name: 'purposeComponent',
        required: false,
        type: 'string',
        example: 'string',
      }],
    },
  },
};
