const Joi = require('@hapi/joi');

exports.createOrUpdateDefine = () => Joi.object().keys({
  purposeStatement: Joi.number().integer().min(1).max(7),
  year: Joi.string().allow(''),
  city: Joi.string().allow(''),
  familyClass: Joi.string().allow(''),
  familyRelations: Joi.string().allow(''),
  immediateFamily: Joi.string().allow(''),
  college: Joi.string().allow(''),
  major: Joi.string().allow(''),
  industry: Joi.string().allow(''),
  position: Joi.string().allow(''),
  childLove: Joi.string().allow(''),
  career: Joi.string().allow(''),
  momInspired: Joi.string().allow(''),
  momTaught: Joi.string().allow(''),
  dadInspired: Joi.string().allow(''),
  dadTaught: Joi.string().allow(''),
  parentsLesson: Joi.string().allow(''),
  adultDecision: Joi.string().allow(''),
  adversity: Joi.string().allow(''),
  talent1: Joi.string().allow(''),
  talent2: Joi.string().allow(''),
  talent3: Joi.string().allow(''),
  teachAbout: Joi.string().allow(''),
  improveArea: Joi.string().allow(''),
  passion1: Joi.string().allow(''),
  passion2: Joi.string().allow(''),
  passion3: Joi.string().allow(''),
  passion4: Joi.string().allow(''),
  peopleHelp: Joi.string().allow(''),
  helpReason: Joi.string().allow(''),
  purposeFinal: Joi.string().allow(''),
  teamFeedback: Joi.string().allow(''),
  purposeVerb: Joi.string().allow(''),
  purposeComponent: Joi.string().allow(''),
});
