const mongoose = require("mongoose");
const scoreConstants = require("../constants/score");

const PurposePulse = mongoose.Schema(
  {
    EE1P: { type: Number, required: true },
    EE2N: { type: Number, required: true },
    EE3P: { type: Number, required: true },
    EE4N: { type: Number, required: true },
    EM1P: { type: Number, required: true },
    EM2N: { type: Number, required: true },
    EM3P: { type: Number, required: true },
    EM4N: { type: Number, required: true },
    EP1P: { type: Number, required: true },
    EP2N: { type: Number, required: true },
    EP3P: { type: Number, required: true },
    EP4N: { type: Number, required: true },
    ER1P: { type: Number, required: true },
    ER2N: { type: Number, required: true },
    ER3P: { type: Number, required: true },
    ER4N: { type: Number, required: true },
    FI1P: { type: Number, required: true },
    FI2N: { type: Number, required: true },
    FI3P: { type: Number, required: true },
    FI4N: { type: Number, required: true },
    FO1P: { type: Number, required: true },
    FO2N: { type: Number, required: true },
    FO3P: { type: Number, required: true },
    FO4N: { type: Number, required: true },
    FS1P: { type: Number, required: true },
    FS2N: { type: Number, required: true },
    FS3P: { type: Number, required: true },
    FS4N: { type: Number, required: true },
    FW1P: { type: Number, required: true },
    FW2N: { type: Number, required: true },
    FW3P: { type: Number, required: true },
    FW4N: { type: Number, required: true },
    IJ1P: { type: Number, required: true },
    IJ2N: { type: Number, required: true },
    IJ3P: { type: Number, required: true },
    IJ4N: { type: Number, required: true },
    IC1P: { type: Number, required: true },
    IC2N: { type: Number, required: true },
    IC3P: { type: Number, required: true },
    IC4N: { type: Number, required: true },
    IA1P: { type: Number, required: true },
    IA2N: { type: Number, required: true },
    IA3P: { type: Number, required: true },
    IA4N: { type: Number, required: true },
    IR1P: { type: Number, required: true },
    IR2N: { type: Number, required: true },
    IR3P: { type: Number, required: true },
    IR4N: { type: Number, required: true },
    LG1P: { type: Number, required: true },
    LG2N: { type: Number, required: true },
    LG3P: { type: Number, required: true },
    LG4N: { type: Number, required: true },
    LP1P: { type: Number, required: true },
    LP2N: { type: Number, required: true },
    LP3P: { type: Number, required: true },
    LP4N: { type: Number, required: true },
    LS1P: { type: Number, required: true },
    LS2N: { type: Number, required: true },
    LS3P: { type: Number, required: true },
    LS4N: { type: Number, required: true },
    LV1P: { type: Number, required: true },
    LV2N: { type: Number, required: true },
    LV3P: { type: Number, required: true },
    LV4N: { type: Number, required: true },
    SF1N: { type: Number, required: true },
    SF2P: { type: Number, required: true },
    SF3P: { type: Number, required: true },
    SF4N: { type: Number, required: true },
    SM1P: { type: Number, required: true },
    SM2N: { type: Number, required: true },
    SM3N: { type: Number, required: true },
    SM4P: { type: Number, required: true },
    SR1P: { type: Number, required: true },
    SR2N: { type: Number, required: true },
    SR3N: { type: Number, required: true },
    SR4P: { type: Number, required: true },
    SW1P: { type: Number, required: true },
    SW2N: { type: Number, required: true },
    SW3P: { type: Number, required: true },
    SW4N: { type: Number, required: true },
    WG1P: { type: Number, required: true },
    WG2N: { type: Number, required: true },
    WG3P: { type: Number, required: true },
    WG4N: { type: Number, required: true },
    WP1P: { type: Number, required: true },
    WP2N: { type: Number, required: true },
    WP3P: { type: Number, required: true },
    WP4N: { type: Number, required: true },
    WS1P: { type: Number, required: true },
    WS2N: { type: Number, required: true },
    WS3P: { type: Number, required: true },
    WS4N: { type: Number, required: true },
    WV1P: { type: Number, required: true },
    WV2N: { type: Number, required: true },
    WV3P: { type: Number, required: true },
    WV4N: { type: Number, required: true },
    completed: { type: Boolean, default: false },
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    token: { type: String, required: true },
  },
  { timestamps: true }
);

module.exports = mongoose.model("PurposePulse", PurposePulse);
